Repository cagallo/rancid-tomatillos, pull requests merged in 2022-02, with the labels that each got.

#8 Feature/display movie ect
  package-lock.json
  src/components/App.js
  src/components/Header.js
  src/components/MovieCard.js
  src/components/MovieContainer.js
  src/components/MoviePoster.js
  src/css/App.css
  src/css/Header.css
  src/css/MovieCard.css
  src/css/MovieContainer.css
  src/css/MoviePoster.css
  src/index.css
  src/logo.png
Labels: Iteration 1

#9 Feature/display individual movie cag
  src/components/App.js
  src/components/MovieContainer.js
  src/components/MoviePoster.js
  src/components/MovieView.js
  src/css/MoviePoster.css
  src/css/MovieView.css
Labels: Iteration 2

#12 Feature/network requests
  package-lock.json
  package.json
  src/apiCalls.js
  src/components/App.js
  src/components/MovieContainer.js
  src/components/MovieView.js
  src/utilities.js
Labels: Iteration 3

#13 Feature/display trailer cag
  package-lock.json
  src/apiCalls.js
  src/components/App.js
  src/components/MovieView.js
  src/components/Trailer.js
  src/utilities.js
Labels: Iteration 3

#19 Feature/error handling ect
  package-lock.json
  src/components/App.js
  src/components/MovieView.js
  src/components/Trailer.js
  src/utilities.js
Labels: Iteration 3

#24 Feature/movie view styling ect
  src/components/App.js
  src/components/MoviePoster.js
  src/components/MovieView.js
  src/components/Trailer.js
  src/css/App.css
  src/css/Header.css
  src/css/MoviePoster.css
  src/css/MovieView.css
  src/css/Trailer.css
  src/utilities.js
Labels: Iteration 3

#30 Add missing property key in handlePosterClick
  src/components/App.js
Labels: bug, refactor

#31 Feature/acceptance testing ect
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/landing_page_spec.js
  cypress/integration/movie_view_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: Iteration 3

#35 Feature/react router ect
  cypress/integration/landing_page_spec.js
  cypress/integration/movie_view_spec.js
  package-lock.json
  package.json
  src/components/App.js
  src/components/MovieContainer.js
  src/components/MoviePoster.js
  src/components/MovieView.js
  src/css/App.css
  src/index.js
Labels: Iteration 4

#37 Feature/create back button functionality cag
  cypress/integration/landing_page_spec.js
  cypress/integration/movie_view_spec.js
  package-lock.json
  src/components/MovieView.js
  src/css/MovieView.css
Labels: Iteration 4

#38 Feature/create tests back button
  cypress/integration/landing_page_spec.js
  cypress/integration/movie_view_spec.js
  src/components/App.js
  src/css/MovieView.css
Labels: Iteration 4

#45 Feature/responsive design ect
  src/Rancid-Tomatillos-oneline.png
  src/components/Header.js
  src/components/MovieDetails.js
  src/css/Header.css
  src/css/MovieDetails.css
  src/css/MoviePoster.css
  src/css/MovieView.css
Labels: enhancement, Iteration 5

#49 Refactor/acceptance testing ect
  cypress/integration/landing_page_spec.js
  cypress/integration/movie_view_spec.js
Labels: refactor

#55 Feature/css animations ect
  package-lock.json
  package.json
  src/components/MovieContainer.js
  src/components/MovieDetails.js
  src/components/Trailer.js
Labels: enhancement

#54 Refactor alt text to be dynamic, and fixed a few linter errors
  package.json
  src/components/MovieDetails.js
  src/components/MoviePoster.js
  src/utilities.js
Labels: refactor

#57 Refactor responsive styling for mobile/tablet views
  src/css/MovieContainer.css
Labels: refactor
